name: composite

description: calculator to test composite actions

inputs:
  number1:
    description: 'first number'
    required: true
    default: "0"

  number2:
    description: 'second number'
    required: true
    default: "0"

outputs:
  result:
    description: 'result'
    value: ${{ steps.sum-result.outputs.result }}

runs:
  using: composite
  steps:
    - shell: bash
      id: sum-result
      run: |
        num1=${{ inputs.number1 }}
        num2=${{ inputs.number2 }}
        result=$((num1 + num2))
        echo "result: $result"
        echo "result=$result" >> "$GITHUB_OUTPUT"
